### ISSUE TITLE
How to get the EIT Dataset?

### ISSUE THREAD

**Issue by wangweiwei104** [jinxixiang/FISTA-Net#1]
Thanks for your excellent work!

And, where can I download the EIT dataset to run your code? 
Can you tell me the website?

Thanks!

**Comment by jinxixiang** [comment]
Hi, we generated the training dataset using COMSOL Multiphysics, as also described in our paper. As the paper is still under review, we might not make the data publicly available at this stage. But you can follow the methodology of solving the forward problem of EIT to get your own dataset, and also design the customized phantom for your own problem. Cheers!
